source :rubygems
gem 'nanoc',      '~>3.1'
gem 'haml',       '~>3.0'
gem 'compass',    '~>0.1'
gem 'compass-susy-plugin', '~>0.8'
gem 'rainpress',  '~>1.0'
gem 'jsmin',      '~>1.0'
#gem 'deadweight', '~>0.1'
#gem 'kramdown',   '~>0.10'
#gem 'typogruby',  '~>1.0'
gem 'builder'
